// Supabase client configuration variables
window.SUPABASE_URL = "https://zkbmelptvfcbyktfesro.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprYm1lbHB0dmZjYnlrdGZlc3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0Nzc0ODIsImV4cCI6MjEwMTA1MzQ4Mn0.4r-FWggFnNC7Ouxs4gr_tpnsI783_o7y-bAcvEr20Z0";
